### ISSUE TITLE
No css directory

### ISSUE THREAD

**Issue by Yoshi0333** [codysnider/tt-rss#17]
I attempted a fresh install of this project on my own webserver and ran into some trouble. When trying to open the site, php just threw a blank page at me. Looking at the logs, it seems that php was looking for a "css/default.css" and couldn't find it. I then noticed that this fork doesn't have a css directory, whereas the original tt-rss does. Is this intentional? Did I miss something?

**Comment by codysnider** [comment]
It's been moved to `/public/css`. It's generally a good practice to separate things like the index.php (or any accessible file that executes) from static resources.

A base install won't do much at the current state. There is a lot of moving around to get the new framework going. However, if you do pull a copy, be sure to use the docker-compose setup instead of installing it locally.

**Comment by Yoshi0333** [comment]
Gotcha, thanks!
